kind = "web"
previewPath = "/"
title = "Merced's Trading Bot"
version = "1.0.0"
id = "artifacts/merced-trading-bot"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24305

[services.development]
run = "pnpm --filter @workspace/merced-trading-bot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/merced-trading-bot", "run", "build" ]
publicDir = "artifacts/merced-trading-bot/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24305"
BASE_PATH = "/"
